README.md
=> Test pull request -- Updated db names in readme. #issue

public/index.html
=> changed title of index.html

public/index.html
=> Updated title again to test committing and github showing up on slack.  #issue

server/db/models/index.js, server/db/models/product.js, server/db/models/product.spec.js
- [x ] added unit tests (or none needed)
---
=> Created the Product model with fields specified in schema -- issue #4

server/api/index.js, server/api/products.js, server/api/products.spec.js
- [ x] added unit tests (or none needed)
- [x ] referenced any relevant issues (or none exist)
---
'refactor all products api route to return object that looks like: {id1: {product1}, id2: {product2}, etc.}'
=> added /api/products get route-#6

client/components/AllProducts.js, client/components/AllProductsContainer.js, client/components/navbar.js, client/routes.js, client/store/allproducts.js, client/store/index.js, client/store/user.js, package-lock.json
Basic functionality for all products page
-- all products component
-- all products reducer
---
=> Dd frontend allproducts

client/components/AllProducts.js, client/components/all-products.spec.js, client/components/user-home.spec.js, client/store/allproducts-store.spec.js, client/store/allproducts.js, client/store/index.js
Added tests to AllProducts component and store.
=> added tests for all products store and component

package-lock.json, package.json, server/auth/facebook.js
… and google.js strategy file
- [x ] added unit tests (or none needed)
- [x ] referenced any relevant issues (or none exist)
---
=> initialized facebook strategy file with boilerplate via passport docs…  #14

client/components/AddToCart.js, client/components/AllProducts.js, client/components/AllProductsContainer.js, client/store/cart.js, client/store/index.js
addToCart button added to allProducts page, state is logging to console. having issues with mapDispatch.
---
=> All products cart features

client/components/SingleProduct.js, client/components/SingleProductContainer.js, client/components/single-product.spec.js, client/routes.js, package-lock.json
Added single product page and made a test for it.
=> added front routes and test for single product pages

client/components/AllProducts.js, client/components/navbar.js
added navlinks to pages for easier navigation
=> added navlinks to pages for easier navigation

server/api/products.js, server/index.js
=> User cookie attachment #18

server/db/models/activeOrder.js, server/db/models/index.js
activeOrders model created and seed file updated
---
=> Active orders model

server/auth/index.js
=> fixed auth router bug

server/api/products.js, server/api/products.spec.js, server/index.js
- [ x] added unit tests (or none needed)
---
'/api/products' response now has following shape:
{
cookieId: 'ghg372h5go8yghuyi3be' || null,
productsById: { id1: {product1}, id2: {product2}, ... },
products: [ id1, id2, ... ]
}
So you can now map over all products as follows:
products.map(id => {
const product = productsById[ id ];
...
});
=> finished implementing indexing for products state. All tests passing  #26

server/auth/facebook.js, server/auth/google.js, server/db/models/user.js
=> tested googlestrategy #30

client/components/auth-form.js
=> added facebook login option #33

seedfile.js, server/db/models/product.js
=> seedfileupdated

client/app.js, client/components/Footer.js, client/components/ViewCart.js, client/components/ViewCartContainer.js, client/components/navbar.js, client/components/user-home.js, client/routes.js, public/style.css
=> added footer and view cart component

client/components/CheckoutForm/CountriesDropdown.js, client/components/CheckoutForm/index.js
=> checkout form scaffolded, ready for stripe  #50

client/components/AddToCart.js, client/components/ViewCart.js, client/components/ViewCartContainer.js, client/store/cart.js, server/api/activeOrders.js, server/db/models/activeOrder.js, server/db/models/index.js
=> activeorder post routes working/addtocart

client/components/UserAccount.js, client/store/user.js, server/api/users.js
Deleting user account works and redirects to log in page
---
=> deleting account is functional

client/components/AllProducts.js, client/components/AllProductsContainer.js, client/components/ViewCart.js, client/components/ViewCartContainer.js, client/routes.js, client/store/cart.js, server/api/activeOrders.js, server/api/products.js
implemented cart crud, everything is working, just need to add some front-end pieces to the mix
---
=> cart CRUD #59

client/components/CheckoutForm/CountriesDropdown.js, client/components/CheckoutForm/StripeCheckoutForm.js, client/components/CheckoutForm/index.js, client/index.js, client/routes.js, package-lock.json, package.json, public/index.html, public/style.css
Added Stripe functionality to the Checkout component. Remember to npm-install for Stripe related modules!
=> Added Stripe functionality

client/components/AddToCart.js, client/components/AllProducts.js, client/components/AllProductsContainer.js, client/components/DisplaySidebar.js, client/components/Sidebar.js, client/components/all-products.spec.js, client/store/index.js, client/store/sidebar.js
basic sidebar button functionality for all products
---
=> All products sidebar

client/components/AllProducts.js
=> fixed bug - unterminated div

client/components/CheckoutForm/CountriesDropdown.js, client/components/CheckoutForm/StatesDropdown.js, client/components/CheckoutForm/StripeCheckoutForm.js, client/components/CheckoutForm/index.js, client/store/index.js, client/store/pastOrders.js, package-lock.json, server/api/index.js, server/api/pastOrders.js, server/db/models/pastOrder.js
Checkout button now adds to the pastOrders model in our db. Cleaned up some code in store/index.js.
=> Stripe adds to Db

client/components/AllProducts.js, client/components/SingleProduct.js, client/components/add-to-cart.spec.js, client/components/all-products.spec.js, client/components/auth-form.js, client/components/display-sidebar.spec.js, client/components/navbar.js, client/components/navbar.spec.js, client/components/sidebar.spec.js, client/components/single-product.spec.js, package-lock.json, package.json
- [ x] added unit tests (or none needed)
---
Added/fleshed out tests for following components:
- AddToCart
- AllProducts
- DisplaySidebar
- Navbar
- Sidebar
- SingleProduct
Have not added tests for container or form components. I figure logic for these can be tested via Redux specs.
My plan for tomorrow is to finish up component tests (UserAccount, ViewCart), add/flesh out Redux tests (action creators, thunks, reducers), and then add Flexbox to display components like we'd drawn in wireframes, as well as the design pattern Geoff had mentioned to not expose api routes to …
=> Component tests #66

client/components/AllProducts.js, client/components/AllProductsContainer.js, client/components/Sidebar.js, client/components/SidebarContainer.js, client/store/index.js, client/store/sidebarFilter.js, public/style.css, seedfile.js, server/db/models/product.js
sidebar working, reset button partial functionality (resets state but not input buttons).
also made updates to seed and products model on this branch, so make sure to re-seed when you merge this.
---
=> Sidebar filter

client/components/CheckoutForm/StripeCheckoutForm.js, client/components/CheckoutForm/index.js, client/components/ViewCart.js, client/routes.js, package-lock.json, package.json, server/api/pastOrders.js, server/db/models/pastOrder.js
Stripe can charge the total associated with the order and the pastOrders model was updated to include total. Remember to re-seed! Also do a npm install because a new stripe module was installed to make charges work.
=> Stripe now charges total and total is added to our DB

client/components/single-product.spec.js, client/store/allproducts-store.spec.js, client/store/allproducts.js, client/store/cart-store.spec.js, client/store/cart.js, client/store/pastOrders-store.spec.js, client/store/pastOrders.js
- [ x] added unit tests (or none needed)
---
Specs for 
- all products
- cart
- past orders (little bit)
=> Redux tests #77

client/components/AllProducts.js, client/components/Footer.js, client/components/auth-form.js, client/components/navbar.js, public/style.css
flexbox support for all products view added, as for a few other components. have yet to get to single product or cart. can continue later
---
=> adding flexbox support for components

client/components/UserAccount.js, client/components/ViewCart.js, client/components/single-product.spec.js, client/components/user-accout.spec.js, client/components/view-cart.spec.js
- [x ] added unit tests (or none needed)
---
Specs for UserAccount and ViewCart
=> Component tests contd #66

client/components/ViewCart.js, client/components/ViewCartContainer.js, client/store/cart.js, client/store/distance.js, client/store/index.js, package-lock.json, package.json, public/index.html, webpack.config.js
=> added cart ui and google distance matrix

client/store/cart.js
- [x ] referenced any relevant issues (or none exist)
---
=> fixed bug - can now adjust item amounts w/o app crashing

client/components/AllProducts.js, client/components/HomePage.js, server/api/pastOrders.js
=> fixed bugs for deploy

client/components/OrderConfirmation.js, client/components/OrderConfirmationContainer.js, client/store/cart.js, client/store/pastOrders.js, server/api/activeOrders.js, server/db/models/activeOrder.js
fixed negative quantity in cart bug, implemented method to delete rows from activeOrders table on order confirmation
---
=> fixed negative quantity in cart bug, implemented method to delete rows in activeOrders

client/components/navbar.js, server/api/activeOrders.js, server/api/products.js, server/utils/arrayToObjectById.js, server/utils/makeSearchFilter.js
refactored dataArrToObj and makeSearchFilter utils for backend routes
---
=> utility functions for backend routes - arrayToObjectById, makeSearchFilter

server/api/pastOrders.js, server/api/users.js, server/api/utils.js
- Added in gatekeeper middleware isAdminOrSelf to users and pastOrders
- deleted password from user put route return data
- created utils file for gatekeeper middleware
---
=> security second pass

client/components/AddToCart.js, client/components/AllProducts.js, client/components/HomePage.js
expanded products link to include image
---
=> expanded products link to include image

server/db/models/product.js
needed to update priceRange virtual column logic after price type was changed to integer
---
=> fixed priceRange issue in products model

client/components/AllProducts.js, client/components/SingleProduct.js
added addToCart button to single products page
---
=> Single products page

client/components/CheckoutForm/CountriesDropdown.js, client/components/CheckoutForm/index.js, client/components/OrderConfirmation.js, client/components/OrderConfirmationContainer.js, client/components/UserAccount.js, client/components/myOrders.js, client/components/myOrdersContainer.js, client/components/singleOrder.js, client/components/singleOrderContainer.js, client/routes.js, client/store/index.js, client/store/itemsPurchased.js, client/store/pastOrders.js
Confirmation page has all the information we want now! Will work on User's past orders page next
=> quantity of items ordered and total price shows up in confirmation page

client/components/CheckoutForm/StripeCheckoutForm.js, client/components/singleOrder.js, client/components/singleOrderContainer.js, client/store/itemsPurchased.js, server/api/pastOrders.js, server/db/models/index.js, server/db/models/productsByOrder.js
Remember to re-seed database! The join table has been changed completely.
=> fixed quantity to show in past orders page as well as confirmation page

client/components/navbar.js
view cart icon now showing for logged in users
---
=> view cart icon now showing for logged in users
